- name: Crear archivos
  hosts: localhost
  gather_facts: yes
  vars:
    nombre: "martin"
    apellido: "esquivel"
    division: "113"
  tasks:
    - name: Obtener datos
      set_fact:
        ip: "{{ ansible_default_ipv4.address }}"
        distro: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
        cores: "{{ ansible_processor_cores }}"

    - name: Crear datos_alumno.txt
      ansible.builtin.template:
        src: datos_alumno.j2
        dest: /tmp/2do_parcial/alumno/datos_alumno.txt

    - name: Crear datos_equipo.txt
      ansible.builtin.template:
        src: datos_equipo.j2
        dest: /tmp/2do_parcial/equipo/datos_equipo.txt

